categories:
  - name: Языковая победа
    id: language
    items:
      - name: C++
        items:
          - domain: плюсыпобеда.рф
      - name: Bash
        items:
          - domain: башпобеда.рф
      - name: Go
        items:
          - domain: гопобеда.рф
      - name: JavaScript
        items:
          - domain: жспобеда.рф
      - name: Lua
        items:
          - domain: луапобеда.рф
      - name: HTML
        items:
          - domain: хтмлпобеда.рф
      - name: TypeScript
        items:
          - domain: тайпскриптпобеда.рф
            ignore: true
            comment: домен угнан
          - domain: тайпскрипт.победапобеда.рф
      - name: Pascal
        items:
          - domain: паскальпобеда.рф
      - name: Python
        items:
          - domain: питонпобеда.рф
      - name: Rust
        items:
          - domain: растпобеда.рф
            ignore: true
            comment: домен угнан
          - domain: раст.победапобеда.рф
      - name: V
        items:
          - domain: випобеда.рф
      - name: Scheme
        items:
          - domain: схемапобеда.рф
      - name: Swift
        items:
          - domain: свифтпобеда.рф
      - name: Haskell
        items:
          - domain: хаскеллпобеда.рф
  - name: Линуксовая победа
    id: linux
    items:
      - name: Linux
        items:
          - domain: линукспобеда.рф
      - name: Arch Linux
        items:
          - domain: арчпобеда.рф
      - name: Gentoo Linux
        items:
          - domain: гентупобеда.рф
      - name: Yocto Linux
        items:
          - domain: йоктопобеда.рф
      - name: Nix
        items:
          - domain: никспобеда.рф
  - name: Остальное
    id: other
    items:
      - name: Конки / Konqi
        items:
          - domain: конкипобеда.рф
      - name: Beget
        items:
          - domain: бегетпобеда.рф
      - name: Магия по контракту
        items:
          - domain: магияпоконтракту.рф
            ignore: true
            comment: домен угнан
          - domain: магияпоконтракту.победапобеда.рф
      - name: Navidrome
        items:
          - domain: навидромпобеда.рф
            comment: "данные: `user / password`, работает с переменной доступностью"
      - name: ESP32
        items:
          - domain: есп32победа.рф
      - name: STM32
        items:
          - domain: стм32победа.рф
            ignore: true
          - domain: стм32.победапобеда.рф
      - name: МТУСИ
        items:
          - domain: мтусипобеда.рф
      - name: ИТМО
        items:
          - domain: итмопобеда.рф
      - name: Окабефон (что)
        items:
          - domain: окабефонпобеда.рф
      - name: MAX
        items:
          - domain: макспобеда.рф
            comment: работает даже на xbt573/awesome-pobeda
  - name: Поражения
    id: loses
    items:
      - name: Rust
        items:
          - domain: растпоражение.рф
      - name: Go
        items:
          - domain: гопоражение.рф
  - name: Кладбище побед
    id: graveyard
    items:
      - name: C
        items:
        - domain: сипобеда.рф
          ignore: true
          comment: исходный код утерян 
      - name: Java
        items:
          - domain: жавапобеда.рф
            ignore: true
      - name: Kotlin
        items:
          - domain: котлинпобеда.рф
            ignore: true
      - name: Elixir
        items:
          - domain: эликсирпобеда.рф
            ignore: true
      - name: svo.ru
        items:
          - domain: svo.ru
            ignore: true
      - name: Valorant
        items:
          - domain: валорантпобеда.рф
            ignore: true
            comment: какая нахуй рукодельница?
      - name: RISC-V
        items:
          - domain: рисквпобеда.рф
            ignore: true
