name: Generate README.md
on:
  push:
    paths:
      - 'service/*'
  workflow_dispatch:
  schedule:
      - cron: '0 0 * * *'
permissions:
  contents: write
jobs:
  generate-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-go@v5
      - run: go mod download && go build
        working-directory: service
      - name: Generate README.md
        working-directory: service
        run: |
          ./service > ../README.md
          
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add ../README.md
          git commit -m "Update from $(git rev-parse --short=8 HEAD)" || :
          git push || :
